Support ECR in Windows Environment
rancher/rancher-catalog pull request #1089
Opened 2018-03-07 04:28 UTC by orangedeng

Related issue https://github.com/rancher/rancher/issues/12018
Add a new catalog entry for Rancher ECR Windows.

2018-03-08 19:22 UTC, deniseschannon requested changes

2018-03-08 19:22 UTC, deniseschannon commented on infra-templates/ecr-windows/0/docker-compose.yml.tpl
> +  image: rancher/rancher-ecr-credentials-windows:v2.0.1
Please update to:  `v3.0.0`

2018-03-08 19:22 UTC, deniseschannon commented on infra-templates/ecr-windows/0/rancher-compose.yml
> +  version: "v2.0.1"
Please update to:  `v3.0.0`

2018-03-08 19:22 UTC, deniseschannon commented on infra-templates/ecr-windows/0/rancher-compose.yml
> +  minimum_rancher_version: "v1.6.14"
Please update to `v1.6.15-rc1`

2018-03-08 19:22 UTC, deniseschannon commented on infra-templates/ecr-windows/config.yml
> +version: v2.0.1
v3.0.0

2018-03-09 02:07 UTC, orangedeng commented
@deniseschannon Updated

2018-03-09 03:10 UTC, deniseschannon commented
LGTM

2018-03-09 03:10 UTC, merged