Upgrade to rancher/convoy-agent:v0.12.0
rancher/rancher-catalog pull request #201
Opened 2016-09-13 19:58 UTC by cjellick

2016-10-02 18:37 UTC, janeczku requested changes

2016-10-02 18:37 UTC, janeczku commented on templates/convoy-nfs/5/rancher-compose.yml
> +    version: "v0.4.0"
The version must be `v0.5.0`

2016-10-16 17:43 UTC, janeczku commented
ping @cjellick

2016-11-12 04:33 UTC, jabenninghoff commented
can this PR be fixed and merged? The version of convoy-nfs in the catalog is still broken.

2016-11-24 00:44 UTC, deniseschannon commented
Closing as we're moving to rancher-nfs

2016-11-24 00:44 UTC, closed without merging

2016-11-25 15:50 UTC, jabenninghoff commented
Am I missing something? Isn't Convoy-NFS how you add rancher-nfs support? Frankly, issues like this have led me to give up on trying to use Rancher/RancherOS.

2016-11-25 17:19 UTC, deniseschannon commented
@jabenninghoff We are moving to a new rancher-nfs solution in 1.2.0, which will not be using convoy anymore. 

http://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/