cifs catalog
rancher/rancher-catalog pull request #612
Opened 2017-04-26 20:21 UTC by mfar-bcgdv

https://github.com/rancher/storage/pull/53

2017-06-04 09:40 UTC, dominicporteous approved these changes

2017-06-30 21:31 UTC, deniseschannon commented
https://github.com/rancher/rancher/issues/9206

2017-07-06 23:53 UTC, LLParse commented
We should consider renaming this plugin from `rancher-cifs` to `rancher-azurefs` or similar because the hard-coded configuration options are specific to Azure File Service.

2017-07-06 23:58 UTC, LLParse requested changes
Just a few minor tweaks, but otherwise this is looking good.

2017-07-06 23:58 UTC, LLParse commented on infra-templates/cifs/0/docker-compose.yml
> +      MOUNT_OPTS: '${CIFS_VERS},user=${USER},password=${PASSWORD},${MOUNT_OPTS}'
We should add `RANCHER_DEBUG: '${RANCHER_DEBUG}'` so the debug flag functions

2017-07-06 23:58 UTC, LLParse commented on infra-templates/cifs/0/docker-compose.yml
> +    image: rancher/storage-cifs:v0.1
This will need to be modified once we release the storage plugin

2017-07-06 23:58 UTC, LLParse commented on infra-templates/cifs/0/rancher-compose.yml
> +    - variable: SCOPE
Scope and Volume Access Mode really shouldn't be configurable. We should just hard-code them to environment/multiHostRW, respectively.

2017-09-20 10:17 UTC, Daxten commented
hey this looks quite usefull for me, is there still work required here?

2019-01-04 00:25 UTC, alena1108 commented
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

2019-01-04 00:25 UTC, closed without merging